services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    volumes:
      - ./actual-data:/data
    restart: unless-stopped
    healthcheck:
        test: bash -c 'cat < /dev/null > /dev/tcp/localhost/5006'
        interval: 5s
        timeout: 10s
        retries: 10

  actual-ai:
    image: docker.io/sakowicz/actual-ai:latest
    restart: unless-stopped
    depends_on:
      actual_server:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - ACTUAL_SERVER_URL=http://actual_server:5006
      - ACTUAL_PASSWORD=${ACTUAL_PASSWORD}
      - ACTUAL_BUDGET_ID=${ACTUAL_BUDGET_ID} # This is the ID from Settings → Show advanced settings → Sync ID
      - CLASSIFICATION_SCHEDULE_CRON=* */4 * * *
      - CLASSIFY_ON_STARTUP=true
      - SYNC_ACCOUNTS_BEFORE_CLASSIFY=false # Whether to sync accounts before classification
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=llama3.1 # optional. required if you want to use a specific model, default is "gpt-3.5-turbo-instruct"
      - OPENAI_BASE_URL=http://ollama:11434/v1 # optional. required if you don't want to use the OpenAI API but OpenAI compatible API, ex: "http://ollama:11424/v1
#      - ACTUAL_E2E_PASSWORD= # optional. required if you have E2E encryption
#      - NODE_TLS_REJECT_UNAUTHORIZED=0 # optional. required if you have trouble connecting to Actual server

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
        test: bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'
        interval: 5s
        timeout: 10s
        retries: 10
